#!/usr/bin/env python3
"""
Generates a .env file for the uAgent from the project's .env file.
Run this from the project root: python agent/generate_env.py
"""
import os
import re

def parse_env(path):
    env = {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            if '=' in line:
                key, _, val = line.partition('=')
                env[key.strip()] = val.strip()
    return env

project_env = parse_env('.env')

agent_env_lines = [
    "# Auto-generated by agent/generate_env.py",
    "# These values come from your project's .env file",
    "",
    f"SUPABASE_URL={project_env.get('VITE_SUPABASE_URL', '')}",
    f"SUPABASE_ANON_KEY={project_env.get('VITE_SUPABASE_ANON_KEY', '')}",
    "",
    "# Change this to generate a unique agent identity/wallet",
    "AGENT_SEED=polygon-mempool-signal-agent-v1",
    "",
    "# Optional: only needed if the agent writes directly to Supabase",
    "# (the edge function handles writes with the service role key)",
    f"SUPABASE_SERVICE_ROLE_KEY={project_env.get('SUPABASE_SERVICE_ROLE_KEY', '')}",
]

with open('agent/.env', 'w') as f:
    f.write('\n'.join(agent_env_lines) + '\n')

print("Created agent/.env with the following:")
print(f"  SUPABASE_URL = {project_env.get('VITE_SUPABASE_URL', 'MISSING')[:40]}...")
print(f"  SUPABASE_ANON_KEY = {project_env.get('VITE_SUPABASE_ANON_KEY', 'MISSING')[:20]}...")
print()
print("To run the agent:")
print("  cd agent")
print("  source .env")
print("  pip install uagents")
print("  python mempool_signal_agent.py")
