/*
# Agent Wallet and Withdrawal Management

## Purpose
Adds wallet management infrastructure for the Fetch.ai agent. The agent has a
real on-chain wallet (fetch1... address) that receives FET token payments from
other agents and can send tokens to external addresses. This migration tracks
the wallet state, deposits, and withdrawal requests.

## New Tables

1. `agent_wallet` — Tracks the agent's on-chain wallet state.
   - `id` (uuid PK)
   - `wallet_address` (text, unique) — The fetch1... mainnet address
   - `agent_address` (text) — The uAgent address (agent1... format)
   - `balance_fet` (numeric) — Last known on-chain balance in FET
   - `balance_updated_at` (timestamptz) — When balance was last synced
   - `network` (text) — 'mainnet' or 'testnet'
   - `seed_phrase_set` (boolean) — Whether the seed has been configured
   - `created_at` (timestamptz)

2. `wallet_transactions` — On-chain wallet transactions (deposits and withdrawals).
   - `id` (uuid PK)
   - `wallet_address` (text) — The agent's wallet address
   - `direction` (text) — 'deposit' or 'withdrawal'
   - `counterparty_address` (text) — The other party's address
   - `amount_fet` (numeric) — Amount in FET
   - `tx_hash` (text) — On-chain transaction hash
   - `block_number` (bigint) — Chain block height
   - `status` (text) — 'pending', 'confirmed', 'failed'
   - `description` (text) — Optional description
   - `created_at` (timestamptz)

3. `withdrawal_requests` — User-initiated withdrawal requests.
   - `id` (uuid PK)
   - `destination_address` (text) — Where to send FET
   - `amount_fet` (numeric) — Amount to withdraw
   - `status` (text) — 'pending', 'processing', 'completed', 'failed'
   - `tx_hash` (text, nullable) — On-chain tx hash once sent
   - `requested_at` (timestamptz)
   - `processed_at` (timestamptz, nullable)
   - `error_message` (text, nullable)

## Security
- All tables have RLS enabled.
- Single-tenant app (no sign-in) — policies use `TO anon, authenticated` with
  `USING (true)` because the data is intentionally shared.
- The edge function uses the service role key for writes, bypassing RLS.

## Notes
- The wallet address is generated by the uAgent from the seed phrase.
- On-chain balance is queried via cosmpy (Fetch.ai LedgerClient).
- Withdrawals are executed by the uAgent using cosmpy's send_tokens().
- The edge function stores withdrawal requests; the uAgent polls for pending
  requests and executes them on-chain.
*/

-- Agent wallet state
CREATE TABLE IF NOT EXISTS agent_wallet (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  wallet_address text UNIQUE NOT NULL,
  agent_address text DEFAULT '',
  balance_fet numeric NOT NULL DEFAULT 0,
  balance_updated_at timestamptz,
  network text NOT NULL DEFAULT 'mainnet' CHECK (network IN ('mainnet', 'testnet')),
  seed_phrase_set boolean NOT NULL DEFAULT false,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE agent_wallet ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_agent_wallet" ON agent_wallet;
CREATE POLICY "anon_select_agent_wallet" ON agent_wallet FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_agent_wallet" ON agent_wallet;
CREATE POLICY "anon_insert_agent_wallet" ON agent_wallet FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_agent_wallet" ON agent_wallet;
CREATE POLICY "anon_update_agent_wallet" ON agent_wallet FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_agent_wallet" ON agent_wallet;
CREATE POLICY "anon_delete_agent_wallet" ON agent_wallet FOR DELETE
  TO anon, authenticated USING (true);

-- Wallet transactions (deposits + withdrawals)
CREATE TABLE IF NOT EXISTS wallet_transactions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  wallet_address text NOT NULL,
  direction text NOT NULL CHECK (direction IN ('deposit', 'withdrawal')),
  counterparty_address text NOT NULL,
  amount_fet numeric NOT NULL DEFAULT 0,
  tx_hash text,
  block_number bigint,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'failed')),
  description text DEFAULT '',
  created_at timestamptz DEFAULT now()
);

ALTER TABLE wallet_transactions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_wallet_transactions" ON wallet_transactions;
CREATE POLICY "anon_select_wallet_transactions" ON wallet_transactions FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_wallet_transactions" ON wallet_transactions;
CREATE POLICY "anon_insert_wallet_transactions" ON wallet_transactions FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_wallet_transactions" ON wallet_transactions;
CREATE POLICY "anon_update_wallet_transactions" ON wallet_transactions FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_wallet_transactions" ON wallet_transactions;
CREATE POLICY "anon_delete_wallet_transactions" ON wallet_transactions FOR DELETE
  TO anon, authenticated USING (true);

-- Withdrawal requests
CREATE TABLE IF NOT EXISTS withdrawal_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  destination_address text NOT NULL,
  amount_fet numeric NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
  tx_hash text,
  requested_at timestamptz DEFAULT now(),
  processed_at timestamptz,
  error_message text
);

ALTER TABLE withdrawal_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_withdrawal_requests" ON withdrawal_requests;
CREATE POLICY "anon_select_withdrawal_requests" ON withdrawal_requests FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_withdrawal_requests" ON withdrawal_requests;
CREATE POLICY "anon_insert_withdrawal_requests" ON withdrawal_requests FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_withdrawal_requests" ON withdrawal_requests;
CREATE POLICY "anon_update_withdrawal_requests" ON withdrawal_requests FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_withdrawal_requests" ON withdrawal_requests;
CREATE POLICY "anon_delete_withdrawal_requests" ON withdrawal_requests FOR DELETE
  TO anon, authenticated USING (true);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_wallet_transactions_wallet ON wallet_transactions(wallet_address);
CREATE INDEX IF NOT EXISTS idx_wallet_transactions_created ON wallet_transactions(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_withdrawal_requests_status ON withdrawal_requests(status);
CREATE INDEX IF NOT EXISTS idx_withdrawal_requests_created ON withdrawal_requests(requested_at DESC);
